version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: p2p-wallet-postgres
    environment:
      POSTGRES_DB: p2p_wallet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - p2p-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: p2p-wallet-redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - p2p-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # NestJS Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: p2p-wallet-app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      # Application
      NODE_ENV: production
      PORT: 3000
      
      # Database
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_DATABASE: p2p_wallet
      
      # JWT
      JWT_SECRET: your-super-secret-jwt-key-for-production
      JWT_EXPIRES_IN: 7d
      
      # Redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ""
      
      # Transfer Limits
      DEFAULT_DAILY_LIMIT: 10000
      DEFAULT_MONTHLY_LIMIT: 100000
    ports:
      - "3000:3000"
    networks:
      - p2p-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Development database (for local development)
  postgres-dev:
    image: postgres:15-alpine
    container_name: p2p-wallet-postgres-dev
    environment:
      POSTGRES_DB: p2p_wallet_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - p2p-network
    profiles:
      - dev

  # Development Redis (for local development)
  redis-dev:
    image: redis:7-alpine
    container_name: p2p-wallet-redis-dev
    volumes:
      - redis_dev_data:/data
    ports:
      - "6380:6379"
    networks:
      - p2p-network
    profiles:
      - dev

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  postgres_dev_data:
    driver: local
  redis_dev_data:
    driver: local

networks:
  p2p-network:
    driver: bridge 